apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:

    - name: pytest
      image: qnib/pytest:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2

    - name: docker-client
      image: docker:19.03.1
      command: ['sleep', '99d']
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

    - name: docker-daemon
      image: docker:19.03.1-dind
      args: ["--insecure-registry 192.168.64.6:32000"]
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true
      volumeMounts:
        - name: cache
          mountPath: /var/lib/docker

    - name: kubectl
      image: lachlanevenson/k8s-kubectl:v1.17.17
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      volumeMounts:
        - name: cache
          mountPath: /var/lib/docker
      command: ['sleep', '99d']
      tty: true

  volumes:
    - name: cache
      hostPath:
        path: /tmp
        type: Directory
    - name: m2
      hostPath:
        path: /root/.m2